# Uncomment this line to define a global platform for your project
# platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

require 'fileutils'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

pre_install do |_installer|
  cache_paths = [ENV['PUB_CACHE'] || File.expand_path("~/.pub-cache")]
  packages = [
    {
      name: "flutter_secure_storage",
      version: "9.2.4",
      relative_path: ["ios", "Classes"],
      file: "FlutterSecureStoragePlugin.h",
      content: "#import <flutter_secure_storage/flutter_secure_storage-Swift.h>\n",
    },
    {
      name: "url_launcher_ios",
      version: "6.3.4",
      relative_path: ["ios", "url_launcher_ios", "Sources", "url_launcher_ios", "Resources"],
      file: "PrivacyInfo.xcprivacy",
      content: "{}\n",
    },
  ]

  cache_paths.each do |cache|
    packages.each do |pkg|
      path = File.join(cache, "hosted", "pub.dev", "#{pkg[:name]}-#{pkg[:version]}", *pkg[:relative_path])
      FileUtils.mkdir_p(path)
      File.write(File.join(path, pkg[:file]), pkg[:content])
    end
  end
end

target 'Runner' do
  use_frameworks!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
platform :ios, '12.0'
