# Uncomment this line to define a global platform for your project
# platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

require 'fileutils'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

pre_install do |_installer|
  plugins_dir = File.expand_path(File.join(__dir__, '.symlinks', 'plugins'))
  FileUtils.mkdir_p(plugins_dir)
  {
    'flutter_secure_storage' => File.expand_path(File.join(__dir__, 'Plugins', 'flutter_secure_storage')),
    'url_launcher_ios' => File.expand_path(File.join(__dir__, 'Plugins', 'url_launcher_ios')),
  }.each do |name, source|
    target = File.join(plugins_dir, name)
    next unless File.directory?(source)
    FileUtils.rm_rf(target)
    FileUtils.ln_sf(source, target)
  end
end

target 'Runner' do
  use_frameworks!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
platform :ios, '12.0'
